

import { GoogleGenAI, Modality } from "@google/ai";

const fileToGenerativePart = (base64: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64.split(',')[1],
      mimeType,
    },
  };
};

export const generateInpaintedImage = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const imagePart = fileToGenerativePart(base64Image, mimeType);
    const engineeredPrompt = `You are an expert photo editor. Your task is to perform a realistic inpainting operation. The user has provided an image with a solid white area indicating the region to be modified. Your goal is to replace ONLY this white area with: "${prompt}".

**CRITICAL RULE: IDENTITY PRESERVATION.** If a person is visible in the unmasked parts of the image, it is absolutely crucial that the generated content preserves that person's identity with extreme precision. You MUST maintain their exact facial features (eye shape, nose, mouth), skin tone, hair, and beard style. Do not change the person. The generated parts must look like they belong to the original person.

Furthermore, the generated content must seamlessly blend with the surrounding image. You must match the original image's lighting, shadows, color tone, textures, and overall style. The final result should look like a single, cohesive, and realistic photograph. Do not alter any part of the image outside the white masked area.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          imagePart,
          { text: engineeredPrompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageData = part.inlineData.data;
        const imageMimeType = part.inlineData.mimeType;
        return `data:${imageMimeType};base64,${base64ImageData}`;
      }
    }
    
    throw new Error("No image was generated by the API. The model may have refused the prompt.");

  } catch (error) {
    console.error("Error generating image:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("An unknown error occurred during image generation.");
  }
};


export const generateCharacterImage = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const imagePart = fileToGenerativePart(base64Image, mimeType);
    const engineeredPrompt = `**CRITICAL MISSION: HYPER-REALISTIC, IDENTITY-PRESERVING PHOTOSHOOT (Hubohu Photoshoot)**

**Your Role:** You are a world-class AI photo-generation specialist. Your primary and NON-NEGOTIABLE directive is to preserve the exact identity of the person in the reference photograph. This is the most important rule. Failure to comply is a total failure of the task.

**Input:**
1. A reference photograph of a person.
2. A user prompt describing a new scene: "${prompt}"

**Analysis Protocol (YOU MUST PERFORM THIS INTERNALLY BEFORE GENERATION):**
1.  **Analyze Facial Geometry:** Scrutinize the reference photo. Deconstruct the subject's face into its core geometric components.
    *   **Head Shape:** Note the precise shape of the jaw, chin, cheekbones, and forehead.
    *   **Eye Details:** Analyze the exact shape, size, color, spacing, and eyelid creases. Note the unique glint and shadow.
    *   **Nose Structure:** Map the exact shape of the bridge, the tip, and the size/angle of the nostrils.
    *   **Mouth and Lips:** Capture the exact lip shape, thickness, curvature, and the details of the cupid's bow.
2.  **Analyze Textural Features:**
    *   **Skin:** Perfectly match the skin tone, undertone, and texture. Replicate every facial crease, line, and pore.
    *   **Beard/Stubble:** If present, replicate the exact style, length, density, and color of the facial hair.
    *   **Hair:** Replicate the hair color, texture, style, and hairline from the reference photo.
3.  **Analyze Unique Identifiers:**
    *   Perfectly replicate any moles, scars, freckles, dimples, or other unique markings.

**Generation Directive:**
After completing the analysis, generate a new, photorealistic image that places the **EXACT SAME PERSON (a perfect "hubohu" match)** from the reference photo into the scene described by the user prompt. Do NOT create a "look-alike," a "cousin," or a "similar" person. It must be the **SAME PERSON**.

**Scene Generation:**
*   Create a completely new background, environment, and clothing based *only* on the user's prompt: "${prompt}".
*   The person must be integrated naturally into this new scene, with hyper-realistic lighting, shadows, and reflections that are consistent with the new environment.

**Final Output:** A single, cohesive, high-quality, and photorealistic image where the original person's identity is perfectly preserved and they are seamlessly placed into a new context. Do not alter the person's core identity in any way.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          imagePart,
          { text: engineeredPrompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageData = part.inlineData.data;
        const imageMimeType = part.inlineData.mimeType;
        return `data:${imageMimeType};base64,${base64ImageData}`;
      }
    }
    
    throw new Error("No image was generated by the API. The model may have refused the prompt.");

  } catch (error) {
    console.error("Error generating character image:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("An unknown error occurred during image generation.");
  }
};