import { GoogleGenAI, Modality } from "@google/genai";

const fileToGenerativePart = (base64: string, mimeType: string) => {
  return {
    inlineData: {
      data: base64.split(',')[1],
      mimeType,
    },
  };
};

export const generateInpaintedImage = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const imagePart = fileToGenerativePart(base64Image, mimeType);
    const engineeredPrompt = `You are an expert photo editor. Your task is to perform a realistic inpainting operation. The user has provided an image with a solid white area indicating the region to be modified. Your goal is to replace ONLY this white area with: "${prompt}".

It is absolutely crucial that the generated content features the exact same person visible in the unmasked parts of the image. You MUST preserve the person's facial features, identity, skin tone, and hair style.

Furthermore, the generated content must seamlessly blend with the surrounding image. You must match the original image's lighting, shadows, color tone, textures, and overall style. The final result should look like a single, cohesive, and realistic photograph. Do not alter any part of the image outside the white masked area.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          imagePart,
          { text: engineeredPrompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageData = part.inlineData.data;
        const imageMimeType = part.inlineData.mimeType;
        return `data:${imageMimeType};base64,${base64ImageData}`;
      }
    }
    
    throw new Error("No image was generated by the API. The model may have refused the prompt.");

  } catch (error) {
    console.error("Error generating image:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("An unknown error occurred during image generation.");
  }
};


export const generateCharacterImage = async (
  base64Image: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }

  try {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const imagePart = fileToGenerativePart(base64Image, mimeType);
    const engineeredPrompt = `**CRITICAL MISSION: Identity-Preserving Photoshoot**

**Your Role:** You are a world-class AI photo-generation specialist. Your primary and non-negotiable directive is to preserve the identity of the person in the reference photograph.

**Input:**
1. A reference photograph of a person.
2. A user prompt describing a new scene: "${prompt}"

**Core Task:**
Generate a new, photorealistic image that places the *exact same person* from the reference photo into the scene described by the user prompt.

**ABSOLUTE REQUIREMENTS (Failure to comply is a failure of the task):**

1.  **100% Identity Match:** The person in the generated image MUST be a perfect match to the person in the reference photo. This is the most important rule.
    *   **Facial Features:** Replicate the facial structure, eye shape and color, nose, mouth, chin, and any unique features (moles, scars, etc.) with extreme precision.
    *   **Skin Tone:** Exactly match the skin tone and complexion.
    *   **Hair:** Replicate the hair color, texture, style, and hairline.
    *   **Overall Appearance:** The generated person must be instantly and unmistakably recognizable as the person from the reference photo. Do NOT create a "look-alike" or a "similar" person. It must be the SAME person.

2.  **Scene Generation:**
    *   Create a completely new background, environment, and clothing based *only* on the user's prompt: "${prompt}".
    *   The person should be integrated naturally into this new scene, with appropriate lighting and shadows that match the environment.

**Final Output:**
A single, cohesive, high-quality, and photorealistic image where the original person is seamlessly placed into a new context. Do not alter the person's core identity in any way.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          imagePart,
          { text: engineeredPrompt },
        ],
      },
      config: {
        responseModalities: [Modality.IMAGE],
      },
    });

    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        const base64ImageData = part.inlineData.data;
        const imageMimeType = part.inlineData.mimeType;
        return `data:${imageMimeType};base64,${base64ImageData}`;
      }
    }
    
    throw new Error("No image was generated by the API. The model may have refused the prompt.");

  } catch (error) {
    console.error("Error generating character image:", error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate image: ${error.message}`);
    }
    throw new Error("An unknown error occurred during image generation.");
  }
};
